/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "error": "#ff8577",
        "surface-dim": "#0a100e",
        "surface-container-low": "#111b18",
        "on-primary-container": "#00442c",
        "outline": "#6d857d",
        "outline-variant": "#23352f",
        "tertiary-container": "#4a3b10",
        "secondary-container": "#182b24",
        "surface-container-highest": "#24352f",
        "primary-fixed-dim": "#75daa8",
        "error-container": "#520d11",
        "on-background": "#e2ece9",
        "on-tertiary": "#2e2100",
        "secondary-fixed-dim": "#85d7ad",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#002113",
        "on-secondary": "#003824",
        "on-tertiary-fixed": "#251a00",
        "background": "#0d1513",
        "surface-container-high": "#1b2824",
        "surface": "#0f1715",
        "on-surface": "#e2ece9",
        "primary": "#52b788",
        "on-surface-variant": "#9cb3ab",
        "on-tertiary-container": "#ffd566",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "surface-bright": "#1a2522",
        "surface-tint": "#75daa8",
        "secondary": "#74c69d",
        "surface-variant": "#1c2724",
        "inverse-primary": "#006c48",
        "primary-container": "#1d4432",
        "surface-container": "#15221f",
        "tertiary-fixed": "#ffd778",
        "tertiary": "#e7c268",
        "on-primary": "#003823",
        "surface-container-lowest": "#080e0c",
        "on-secondary-container": "#8fe2b7",
        "inverse-surface": "#e2ece9",
        "secondary-fixed": "#a0f4c8",
        "on-tertiary-fixed-variant": "#5a4400",
        "primary-fixed": "#92f7c3",
        "inverse-on-surface": "#0d1513",
        "on-primary-fixed-variant": "#005235",
        "tertiary-fixed-dim": "#d4b35e"
      },
      fontFamily: {
        headline: ['Literata', 'Georgia', 'serif'],
        display: ['Literata', 'Georgia', 'serif'],
        body: ['Nunito Sans', 'system-ui', 'sans-serif'],
        label: ['Nunito Sans', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
